# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.


#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print("NumPy version:", np.__version__)
print(np.show_config())

NumPy version: 2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: 

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [5]:
array4 = np.array([1,2,3,4,5])
print(array4.nbytes)

40


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)


In [ ]:
vector6 = np.arange(start=10,stop=50)
print(vector6)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
np.sort(vector6)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
vector8 = np.arange(0,9)
vector_8 = vector8.reshape(3,3)
print(vector_8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
vector9 = np.array([1,2,0,0,4,0])
print(vector9[vector9 != 0])

[1 2 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [6]:
identity = np.zeros(9)
identity = identity.reshape(3,3)
for i in [0,1,2] :
  identity[i,i]=1

print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
np.random.random((3,3,3))

array([[[0.65554017, 0.93664756, 0.15947196],
        [0.10645875, 0.11768142, 0.92967248],
        [0.62562806, 0.3117022 , 0.68297572]],

       [[0.79184807, 0.74158174, 0.37708031],
        [0.02955673, 0.21837107, 0.3792336 ],
        [0.27398034, 0.42086436, 0.95694586]],

       [[0.92571678, 0.47887635, 0.04681388],
        [0.07289948, 0.01194303, 0.32966053],
        [0.67436682, 0.30996319, 0.49917939]]])

#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)


In [8]:
random_array = np.random.random((10,10))
print(random_array.min(), random_array.max())

0.003551551367529937 0.9717838079315972


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
random_vector = np.random.random(30)
print(random_vector.mean())

0.4155511828953525


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
array2d = np.zeros((4,4))
array2d[0] = 1
array2d[-1] = 1
array2d[:,0] = 1
array2d[:,-1] = 1
print(array2d)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
#nan, False, False, nan, True, True

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [9]:
matrix16 = np.zeros((5,5))
matrix16[1,0] =1
matrix16[2,1] =2
matrix16[3,2] =3
matrix16[4,3] =4
print(matrix16)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [10]:
matrix17 = np.zeros((8,8))
matrix17[1::2, ::2] =1
matrix17[::2, 1::2] =1
print(matrix17)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [11]:
np.unravel_index(100, (6,7,8))

(np.int64(1), np.int64(5), np.int64(4))

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [12]:
random_matrix = np.random.random((5,5))
mean = np.mean(random_matrix)
var = np.var(random_matrix)
Z = (random_matrix - mean)/var
print(Z)

[[ 1.242346    3.96690014 -3.71700315  1.08741663 -2.44418193]
 [ 3.53379075  3.72219044  4.07611924 -2.83548546  4.17259176]
 [ 2.4205962  -3.97636719 -5.85195271 -4.46093334  0.40322167]
 [-1.45987484 -5.4942497   4.16507435  4.95285754  1.34000743]
 [-1.31686311  2.06909325 -1.01927222 -0.34472631 -4.23129546]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
dtype20 = np.dtype([('Red', np.ubyte), ('Green', np.ubyte), ('Blue', np.ubyte), ('Alpha', np.ubyte)])
print(dtype20)